// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtxmGacJOoWQoaWwVkSIEGZjgOvFSZ-EY',
    appId: '1:363408722266:web:03cc29f235603b16790b63',
    messagingSenderId: '363408722266',
    projectId: 'ecoapp-9254d',
    authDomain: 'ecoapp-9254d.firebaseapp.com',
    storageBucket: 'ecoapp-9254d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3k68f2IjSX-WOV6Iisbdh1hFIRvDhTmc',
    appId: '1:363408722266:android:a521d390e484a10e790b63',
    messagingSenderId: '363408722266',
    projectId: 'ecoapp-9254d',
    storageBucket: 'ecoapp-9254d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAv28BHPXSQ0PYSxL3Yk-rs2r6cOQ6Ixo',
    appId: '1:363408722266:ios:fb7bdfa29ca441ed790b63',
    messagingSenderId: '363408722266',
    projectId: 'ecoapp-9254d',
    storageBucket: 'ecoapp-9254d.appspot.com',
    androidClientId: '363408722266-rrp5pujsa8nocmnulj8c0ob6qta3d58m.apps.googleusercontent.com',
    iosClientId: '363408722266-2folui8hrrba9b6mddnctfudcl389e96.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

}